services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: carspark_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-carspark-secret-key-2025
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carspark_db
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - USE_S3=True
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=eu-north-1
      - AWS_S3_BUCKET_NAME=aslan-auto-img
    volumes:
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python init_db.py && 
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
