# Generated by Django 4.2.10 on 2025-09-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('wagon', 'Универсал'), ('suv', 'Внедорожник'), ('coupe', 'Купе'), ('convertible', 'Кабриолет')], max_length=20, null=True, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем двигателя (л)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='euro_standard',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Евро стандарт'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)'),
        ),
    ]
